layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

dyk:
  - >
    Welcome to my newly-revised website! If this is your first time seeing this slideshow, 
    you'll likely get interrupted while reading this, 
    as the slideshow passively scrolls automatically after five seconds.
  - > 
    I've had a personal website since 2017. This one is a customized fork of Github's 
    personal-website repository. I recently redid the website using Tailwind CSS, so I can more easily 
    adjust portions of the webiste.
  - > 
    I have a music minor. I enjoy listening to all types of music 
    (Rap, R&B, New Wave, and Alternative Rock are some favorites though!) 
    Sometimes I compose my own music for fun. 
    I play percussion in UConn's Percussion Ensemble. I also play guitar in my free time!
  - This Summer, I'm an intern at Pega!
  - I love to rock climb. I've been climbing since I went to college. 
  - > 
    I'm a Microsoft Learn Beta Student Ambassador. In Spring 2021, I hosted a workshop at a 
    Hackathon to help students collaboratively code in Microsoft VSCode using LiveShare.

projects:
  -
    id: dd
    name: Detective Dictator
    author: Me!
    fullAuthor: Finn Navin
    short_desc: >
      My version of the board game "Secret Hitler" -- entirely online! 
    description: > 
      My version of the board game "Secret Hitler" -- entirely online! 
      I made this so I could play one of my favorite board games with my friends while social distancing.
      It took about 2 weeks of focused development in May 2020 to make it fully playable, and gets
      frequent visits from my friends and I. It is now hosted at SecretHitler.js.org, so I removed the original 
      'Detective Dictator' branding.
    accent_color:  "#e56344"
    accent_color_2:  "#036c7c"
    URL: https://secrethitler.js.org
    URL2: https://github.com/FinnCowbell/DetectiveDictator
    style: light
    technologies:
      - Node.js
      - Socket.io
      - Express.js
      - Webpack
      - React
      - Sass
  -
    id: p4gtl
    name: Â¡Please 4get the Lyrics!
    author: The Huskiteers 
    fullAuthor: Finn Navin, Christopher Vassallo, Jacob Dillon, Michael Taylor, Brandon Mino, and Xuan Chau
    short_desc: >
      A Phone-Controlled karaoke guessing game!
    description: >
      Our Team's 2nd-place submission at HackUMass 2019! We wanted to recreate kahoot-style gameplay but 
      take it a step further. We created this Karaoke guessing game as a fun roof of concept of what can be done!
      Hosting a lobby requires a Spotify account, so if you want to host a game you should do it in a new window.
    accent_color: "#bd6d04"
    accent_color_2: "#0d4ff5"
    URL: https://p4gtl.herokuapp.com/
    URL2: https://hackumass-vii-projects.hackumass.com/71.html
    style: light
    technologies:
      - Node.js
      - Socket.io
      - Express.js
      - The Spotify API
      - Karaoke files (.kar)
      - Karapython
  -
    id: nextstep
    name: The Next Step
    author: The Fat Dads
    fullAuthor: Finn Navin, Christopher Vassallo, and Jack Violet
    accent_color: "#8c2629"
    accent_color_2: "#8c2629"
    URL: https://thefatdads.github.io
    style: light
    short_desc: >
      A web-app providing resources and to opioid users and their families in Connecticut.
    description: |
      Our Team's Winning Submission to the 2018 Connecticut Technology Council College Tech Challenge!
      It's a web-app providing resources and to opioid users and their families in Connecticut. It uses 
      data.ct.gov's rest API to access data and display helpful locations on Google Maps.

      Because Google now requires payment to use their maps API, some things may no longer show up correctly.
    technologies:
      - Bootstrap
      - Google Maps API
      - Socrata Open Data API
  -
    id: sov
    name: Spirographs of Venus
    author: Me!
    fullAuthor: Finn Navin
    short_desc: >
      My winning math-visualization project at the 2018 Museum of Mathematics Hackathon!
    description: >
      My winning project at the 2018 Museum of Mathematics Hackathon! Made in 24 hours, this is a version that has been adapted and
      optimized past that time limit for a single player, web experience. 
      The original was created for the Momath "Math Floor": A large, touchscreen floor.

      The project has been featured on the Museums instagram, and another web version was sent to Momath email 
      subscribers in May of 2020! It makes me happy that so many people have been able to enjoy something I made.
    accent_color: '#100030'
    accent_color_2: '#957f00'
    URL: https://finncowbell.github.io/spirographsOfVenus
    URL2: http://hackathon.momath.org/showcase/
    style: light
    technologies:
      - P5.js
      - Momath's Math Floor API
  -
    id: cabbage
    name: Cannonball Cabbage
    author: Somebody
    fullAuthor: Me
    secret: true
    accent_color: '#000'
    accent_color_2: '#000'
    short_desc: >
      Wait, what the heck is this?
    description: >
      It seems you've found a hidden project!
      Please do not ask why I made this, I do not have an answer for you.
    URL: https://finncowbell.github.io/Cannonball-Cabbage/
    technologies:
      - Piskel
      - Logic Pro X
      - Boredom
  -
    id: saucy
    name: Saucy The Sausage
    author: Somebody
    fullAuthor: Me
    secret: true
    accent_color: '#000'
    accent_color_2: '#000'
    short_desc: >
      Wait, what the heck is this?
    description: |
      My buddy Henry made this sprite in hopes of making a sidescrolling game.
      I made this song as the title track for the game.
      It never came to fruition, but I made this as a tribute. 
    URL: https://finncowbell.github.io/saucy/
    technologies:
      - Do you really want to know how the sausage gets made?

github_projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 15
  exclude:
    archived: true
    forks: false
    projects:
    - DetectiveDictator
    - spirographsOfVenus
    - finnnavin2
    - FinnNav.in
    - Cannonball-Cabbage
    - saucy

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  email: thomasfnavin@gmail.com
  linkedin: finnnavin
  github: FinnCowbell
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://finnnav.in
  # youtube: your_username

# topics:
#   - name: CSS
#     web_url: https://github.com/topics/css
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

#   - name: Web design

#   - name: Sass
#     web_url: https://github.com/topics/sass
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
