plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

collections_dir: content
collections:
  projects:
    permalink: /:collection/:name/
    layout: "project"
    sort_by: date
    output: true # Make permalinks/publish as pages
  posts:
    permalink: /:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "project"
    values:
      layout: "project"

dyk:
  - >
    i work at microsoft
  - >
    i like making websites
  - > 
    sometimes i write music
  - >
    i like to rock climb
  - > 
    i live in new york
  - > 
    

github_projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 15
  exclude:
    archived: true
    forks: false
    projects:
    - DetectiveDictator
    - spirographsOfVenus
    - finnnavin2
    - FinnNav.in
    - Cannonball-Cabbage
    - saucy

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: finnnavin
  github: FinnCowbell
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # youtube: your_username

# topics:
#   - name: CSS
#     web_url: https://github.com/topics/css
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

#   - name: Web design

#   - name: Sass
#     web_url: https://github.com/topics/sass
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png

theme: jekyll-theme-minimal
